import type { Metadata } from "next"
import { Montserrat, Merriweather } from "next/font/google"
import "./globals.css"

const Monserrat_init = Montserrat({
  subsets: ["latin"],
  weight: "900",
  variable: "--font-montserrat",
})

const Merriweather_init = Merriweather({
  subsets: ["latin"],
  style: ["italic", "normal"],
  weight: ["400", "700"],
  variable: "--font-merriweather",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${Monserrat_init.variable} ${Merriweather_init.variable} bg-zinc-900 text-white max-w-2xl mx-auto py-10 px-4`}
    >
      <body>{children}</body>
    </html>
  )
}
